# Generated by Django 4.2.1 on 2023-06-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7)),
                ('rating_value', models.IntegerField()),
                ('date_rated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
